# Generated by Django 3.2.9 on 2022-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avater',
            field=models.ImageField(blank=True, default='pic-1.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='images',
            field=models.ImageField(blank=True, default='about-img.png', null=True, upload_to=''),
        ),
    ]
