# Generated by Django 3.2.9 on 2022-03-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritefood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.food'),
        ),
    ]
